### ISSUE TITLE
Metrics on demos

### ISSUE THREAD

**Issue by soundwarrior** [cherryaudio/store-issues#84] opened 2021-07-22 23:21 UTC
### Description:
It would be nice to see metrics on demos and the # of demos that converted into purchases.
Maybe even the number of days to convert from demo to purchase.

**Comment by tstone** [comment] 2021-07-28 03:17
+1

I've made a similar request as well -- https://github.com/cherryaudio/store-issues/issues/8

**Comment by techenby** [comment] 2021-08-03 16:51
Duplicate of #8

**Closed as completed by techenby** 2021-08-03 16:51 UTC
Labels: enhancement
