### ISSUE TITLE
Error message adding .zip file to VM2500 Collection Presets product

### ISSUE THREAD

**Issue by SynthDan** [cherryaudio/store-issues#46] opened 2021-04-01 20:58 UTC
I'm trying to upload a presets .zip file using the Nebula interface (for the Cherry Audio / MRB manufacturer) and it fails in Nebula. I used the old interface and it works correctly.

![image](https://user-images.githubusercontent.com/13699795/113353326-558d5a00-92f2-11eb-95e3-caedd5bc0fbe.png)

**Comment by SynthDan** [comment] 2021-04-01 20:59
Here's the zip file if you wish to reproduce it.

[VM2500 Collection Presets.zip](https://github.com/cherryaudio/store-issues/files/6246444/VM2500.Collection.Presets.zip)

**Comment by soundwarrior** [comment] 2021-04-01 21:09
I looked at the code and it's not using the correct file extension when checking the files.  Maybe this is accidentally using a different preset extension?

**Comment by andymnewhouse** [comment] 2021-04-02 16:00
Ahh the issue is I have the default preset extension as `.preset` instead of `.voltagepreset`

**Comment by andymnewhouse** [comment] 2021-04-02 16:01
Fixed in 3.5.19

**Closed** 2021-04-05 19:25 UTC
Labels: bug, nebula
